version: "3"

volumes:
  users-postgres-data:
    driver: local

services:
  #
  # USERS API
  #
  users-postgres:
    container_name: users-postgres
    image: postgres
    volumes:
      - users-postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  users-api:
    image: microapis/users-api:latest
    ports:
      - 5020:5020
    environment:
      - POSTGRES_DSN=postgres://postgres:postgres@users-postgres:5432/postgres?sslmode=disable
      - HOST=users-api
      - PORT=5020
    depends_on:
      - users-postgres
    links:
      - users-postgres
