// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/users.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Meta struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{0}
}

func (m *Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meta.Unmarshal(m, b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
}
func (m *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(m, src)
}
func (m *Meta) XXX_Size() int {
	return xxx_messageInfo_Meta.Size(m)
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{2}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *User) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type UserGetRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGetRequest) Reset()         { *m = UserGetRequest{} }
func (m *UserGetRequest) String() string { return proto.CompactTextString(m) }
func (*UserGetRequest) ProtoMessage()    {}
func (*UserGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{4}
}

func (m *UserGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetRequest.Unmarshal(m, b)
}
func (m *UserGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetRequest.Marshal(b, m, deterministic)
}
func (m *UserGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetRequest.Merge(m, src)
}
func (m *UserGetRequest) XXX_Size() int {
	return xxx_messageInfo_UserGetRequest.Size(m)
}
func (m *UserGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetRequest proto.InternalMessageInfo

func (m *UserGetRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UserGetResponse struct {
	Data                 *User    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGetResponse) Reset()         { *m = UserGetResponse{} }
func (m *UserGetResponse) String() string { return proto.CompactTextString(m) }
func (*UserGetResponse) ProtoMessage()    {}
func (*UserGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{5}
}

func (m *UserGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetResponse.Unmarshal(m, b)
}
func (m *UserGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetResponse.Marshal(b, m, deterministic)
}
func (m *UserGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetResponse.Merge(m, src)
}
func (m *UserGetResponse) XXX_Size() int {
	return xxx_messageInfo_UserGetResponse.Size(m)
}
func (m *UserGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetResponse proto.InternalMessageInfo

func (m *UserGetResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserGetResponse) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *UserGetResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type UserGetByEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGetByEmailRequest) Reset()         { *m = UserGetByEmailRequest{} }
func (m *UserGetByEmailRequest) String() string { return proto.CompactTextString(m) }
func (*UserGetByEmailRequest) ProtoMessage()    {}
func (*UserGetByEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{6}
}

func (m *UserGetByEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetByEmailRequest.Unmarshal(m, b)
}
func (m *UserGetByEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetByEmailRequest.Marshal(b, m, deterministic)
}
func (m *UserGetByEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetByEmailRequest.Merge(m, src)
}
func (m *UserGetByEmailRequest) XXX_Size() int {
	return xxx_messageInfo_UserGetByEmailRequest.Size(m)
}
func (m *UserGetByEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetByEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetByEmailRequest proto.InternalMessageInfo

func (m *UserGetByEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UserGetByEmailResponse struct {
	Data                 *User    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGetByEmailResponse) Reset()         { *m = UserGetByEmailResponse{} }
func (m *UserGetByEmailResponse) String() string { return proto.CompactTextString(m) }
func (*UserGetByEmailResponse) ProtoMessage()    {}
func (*UserGetByEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{7}
}

func (m *UserGetByEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetByEmailResponse.Unmarshal(m, b)
}
func (m *UserGetByEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetByEmailResponse.Marshal(b, m, deterministic)
}
func (m *UserGetByEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetByEmailResponse.Merge(m, src)
}
func (m *UserGetByEmailResponse) XXX_Size() int {
	return xxx_messageInfo_UserGetByEmailResponse.Size(m)
}
func (m *UserGetByEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetByEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetByEmailResponse proto.InternalMessageInfo

func (m *UserGetByEmailResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserGetByEmailResponse) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *UserGetByEmailResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type UserCreateRequest struct {
	Data                 *User    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreateRequest) Reset()         { *m = UserCreateRequest{} }
func (m *UserCreateRequest) String() string { return proto.CompactTextString(m) }
func (*UserCreateRequest) ProtoMessage()    {}
func (*UserCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{8}
}

func (m *UserCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreateRequest.Unmarshal(m, b)
}
func (m *UserCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreateRequest.Marshal(b, m, deterministic)
}
func (m *UserCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreateRequest.Merge(m, src)
}
func (m *UserCreateRequest) XXX_Size() int {
	return xxx_messageInfo_UserCreateRequest.Size(m)
}
func (m *UserCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreateRequest proto.InternalMessageInfo

func (m *UserCreateRequest) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserCreateResponse struct {
	Data                 *User    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreateResponse) Reset()         { *m = UserCreateResponse{} }
func (m *UserCreateResponse) String() string { return proto.CompactTextString(m) }
func (*UserCreateResponse) ProtoMessage()    {}
func (*UserCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{9}
}

func (m *UserCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreateResponse.Unmarshal(m, b)
}
func (m *UserCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreateResponse.Marshal(b, m, deterministic)
}
func (m *UserCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreateResponse.Merge(m, src)
}
func (m *UserCreateResponse) XXX_Size() int {
	return xxx_messageInfo_UserCreateResponse.Size(m)
}
func (m *UserCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreateResponse proto.InternalMessageInfo

func (m *UserCreateResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserCreateResponse) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *UserCreateResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type UserVerifyPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserVerifyPasswordRequest) Reset()         { *m = UserVerifyPasswordRequest{} }
func (m *UserVerifyPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*UserVerifyPasswordRequest) ProtoMessage()    {}
func (*UserVerifyPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{10}
}

func (m *UserVerifyPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserVerifyPasswordRequest.Unmarshal(m, b)
}
func (m *UserVerifyPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserVerifyPasswordRequest.Marshal(b, m, deterministic)
}
func (m *UserVerifyPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserVerifyPasswordRequest.Merge(m, src)
}
func (m *UserVerifyPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_UserVerifyPasswordRequest.Size(m)
}
func (m *UserVerifyPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserVerifyPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserVerifyPasswordRequest proto.InternalMessageInfo

func (m *UserVerifyPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserVerifyPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserVerifyPasswordResponse struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserVerifyPasswordResponse) Reset()         { *m = UserVerifyPasswordResponse{} }
func (m *UserVerifyPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*UserVerifyPasswordResponse) ProtoMessage()    {}
func (*UserVerifyPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{11}
}

func (m *UserVerifyPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserVerifyPasswordResponse.Unmarshal(m, b)
}
func (m *UserVerifyPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserVerifyPasswordResponse.Marshal(b, m, deterministic)
}
func (m *UserVerifyPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserVerifyPasswordResponse.Merge(m, src)
}
func (m *UserVerifyPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_UserVerifyPasswordResponse.Size(m)
}
func (m *UserVerifyPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserVerifyPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserVerifyPasswordResponse proto.InternalMessageInfo

func (m *UserVerifyPasswordResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *UserVerifyPasswordResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type UserListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListRequest) Reset()         { *m = UserListRequest{} }
func (m *UserListRequest) String() string { return proto.CompactTextString(m) }
func (*UserListRequest) ProtoMessage()    {}
func (*UserListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{12}
}

func (m *UserListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListRequest.Unmarshal(m, b)
}
func (m *UserListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListRequest.Marshal(b, m, deterministic)
}
func (m *UserListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListRequest.Merge(m, src)
}
func (m *UserListRequest) XXX_Size() int {
	return xxx_messageInfo_UserListRequest.Size(m)
}
func (m *UserListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserListRequest proto.InternalMessageInfo

type UserListResponse struct {
	Data                 []*User  `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListResponse) Reset()         { *m = UserListResponse{} }
func (m *UserListResponse) String() string { return proto.CompactTextString(m) }
func (*UserListResponse) ProtoMessage()    {}
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{13}
}

func (m *UserListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListResponse.Unmarshal(m, b)
}
func (m *UserListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListResponse.Marshal(b, m, deterministic)
}
func (m *UserListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListResponse.Merge(m, src)
}
func (m *UserListResponse) XXX_Size() int {
	return xxx_messageInfo_UserListResponse.Size(m)
}
func (m *UserListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserListResponse proto.InternalMessageInfo

func (m *UserListResponse) GetData() []*User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserListResponse) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *UserListResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Meta)(nil), "proto.Meta")
	proto.RegisterType((*Error)(nil), "proto.Error")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*UserGetRequest)(nil), "proto.UserGetRequest")
	proto.RegisterType((*UserGetResponse)(nil), "proto.UserGetResponse")
	proto.RegisterType((*UserGetByEmailRequest)(nil), "proto.UserGetByEmailRequest")
	proto.RegisterType((*UserGetByEmailResponse)(nil), "proto.UserGetByEmailResponse")
	proto.RegisterType((*UserCreateRequest)(nil), "proto.UserCreateRequest")
	proto.RegisterType((*UserCreateResponse)(nil), "proto.UserCreateResponse")
	proto.RegisterType((*UserVerifyPasswordRequest)(nil), "proto.UserVerifyPasswordRequest")
	proto.RegisterType((*UserVerifyPasswordResponse)(nil), "proto.UserVerifyPasswordResponse")
	proto.RegisterType((*UserListRequest)(nil), "proto.UserListRequest")
	proto.RegisterType((*UserListResponse)(nil), "proto.UserListResponse")
}

func init() { proto.RegisterFile("proto/users.proto", fileDescriptor_b1c161a4c7514913) }

var fileDescriptor_b1c161a4c7514913 = []byte{
	// 509 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xfd, 0xec, 0xd8, 0x4e, 0x73, 0xf3, 0x29, 0x90, 0xab, 0xfe, 0xb8, 0x16, 0x15, 0x61, 0x56,
	0x61, 0x41, 0x91, 0xc2, 0x8f, 0xc4, 0x0a, 0x15, 0x14, 0x55, 0x08, 0x2a, 0xa1, 0x41, 0x94, 0x65,
	0x35, 0xc4, 0x17, 0x64, 0xa9, 0xae, 0xcd, 0xcc, 0xa4, 0x25, 0x2c, 0x78, 0x10, 0x5e, 0x90, 0xd7,
	0x40, 0x33, 0xfe, 0x6f, 0xd3, 0xb2, 0xa2, 0x2b, 0xcf, 0xbd, 0xe7, 0xcc, 0x9d, 0x33, 0x67, 0x8e,
	0x61, 0x9c, 0xcb, 0x4c, 0x67, 0x8f, 0x97, 0x8a, 0xa4, 0xda, 0xb7, 0x6b, 0xf4, 0xed, 0x87, 0x05,
	0xe0, 0x1d, 0x91, 0x16, 0xec, 0x19, 0xf8, 0x73, 0x29, 0x33, 0x89, 0x08, 0xde, 0x22, 0x8b, 0x29,
	0x74, 0x26, 0xce, 0xd4, 0xe7, 0x76, 0x8d, 0x21, 0xf4, 0x53, 0x52, 0x4a, 0x7c, 0xa5, 0xd0, 0x9d,
	0x38, 0xd3, 0x01, 0xaf, 0x4a, 0xd6, 0x07, 0x7f, 0x9e, 0xe6, 0x7a, 0xc5, 0x7e, 0x39, 0xe0, 0x7d,
	0x54, 0x24, 0x71, 0x04, 0x6e, 0x12, 0xdb, 0xdd, 0x03, 0xee, 0x26, 0x31, 0x6e, 0x82, 0x4f, 0xa9,
	0x48, 0x4e, 0xcb, 0x9d, 0x45, 0x61, 0x4e, 0x39, 0x13, 0x29, 0x85, 0x3d, 0xdb, 0xb4, 0x6b, 0x8c,
	0x60, 0x23, 0x17, 0x4a, 0x5d, 0x64, 0x32, 0x0e, 0x3d, 0xdb, 0xaf, 0x6b, 0xdc, 0x03, 0x58, 0x48,
	0x12, 0x9a, 0xe2, 0x13, 0xa1, 0x43, 0x7f, 0xe2, 0x4c, 0x7b, 0x7c, 0x50, 0x76, 0x0e, 0xb4, 0x81,
	0x97, 0x79, 0x5c, 0xc1, 0x41, 0x01, 0x97, 0x9d, 0x03, 0xcd, 0x1e, 0xc2, 0xc8, 0x68, 0x3b, 0x24,
	0xcd, 0xe9, 0xdb, 0x92, 0x94, 0xc6, 0x1d, 0xe8, 0x1b, 0x33, 0x4e, 0x6a, 0xa9, 0x81, 0x29, 0xdf,
	0xc4, 0xec, 0x02, 0xee, 0xd4, 0x54, 0x95, 0x67, 0x67, 0x8a, 0xf0, 0x3e, 0x78, 0xb1, 0xd0, 0xc2,
	0x12, 0x87, 0xb3, 0x61, 0xe1, 0xdf, 0xbe, 0x61, 0x71, 0x0b, 0x18, 0x42, 0x4a, 0x5a, 0xd8, 0x1b,
	0x36, 0x04, 0x63, 0x2b, 0xb7, 0x00, 0x32, 0xf0, 0xc9, 0x98, 0x6b, 0xaf, 0x3b, 0x9c, 0xfd, 0x5f,
	0x32, 0xac, 0xe1, 0xbc, 0x80, 0xd8, 0x23, 0xd8, 0x2a, 0x0f, 0x7e, 0xb5, 0x9a, 0x1b, 0x8f, 0x2a,
	0xa9, 0xb5, 0x81, 0x4e, 0xcb, 0x40, 0xf6, 0x13, 0xb6, 0x2f, 0xd3, 0x6f, 0x55, 0xee, 0x53, 0x18,
	0x9b, 0x91, 0xaf, 0xed, 0x13, 0x54, 0x52, 0xff, 0x76, 0x34, 0xfb, 0x01, 0xd8, 0xde, 0x75, 0xab,
	0x8a, 0x8f, 0x60, 0xd7, 0x8c, 0x3c, 0x26, 0x99, 0x7c, 0x59, 0xbd, 0x2f, 0x83, 0x75, 0xa3, 0xc9,
	0x9d, 0x44, 0xba, 0xdd, 0x44, 0xb2, 0x63, 0x88, 0xd6, 0x8d, 0x2b, 0xaf, 0xb4, 0x09, 0xfe, 0xb9,
	0x38, 0x2d, 0xd3, 0xb5, 0xc1, 0x8b, 0xa2, 0x91, 0xe9, 0x5e, 0x2f, 0x73, 0x5c, 0x04, 0xf0, 0x5d,
	0xa2, 0xaa, 0xb0, 0xb2, 0xef, 0x70, 0xb7, 0x69, 0x5d, 0xf1, 0xac, 0xf7, 0xef, 0x3c, 0x9b, 0xfd,
	0x76, 0x61, 0x68, 0x66, 0x7e, 0x20, 0x79, 0x9e, 0x2c, 0x08, 0x9f, 0x43, 0xef, 0x90, 0x34, 0x6e,
	0xb5, 0x8e, 0x6b, 0x7e, 0xaa, 0x68, 0xfb, 0x72, 0xbb, 0xd0, 0xca, 0xfe, 0xc3, 0xb7, 0x00, 0x4d,
	0x52, 0xf1, 0x5e, 0x97, 0xd7, 0xcd, 0x7b, 0xb4, 0x77, 0x0d, 0x5a, 0x0f, 0x7b, 0x09, 0x41, 0x11,
	0x20, 0x0c, 0x5b, 0xd4, 0x4e, 0x12, 0xa3, 0xdd, 0x35, 0x48, 0x3d, 0xe0, 0x13, 0x8c, 0xba, 0xcf,
	0x86, 0x93, 0x16, 0x7d, 0x6d, 0x40, 0xa2, 0x07, 0x37, 0x30, 0xea, 0xc1, 0x2f, 0xc0, 0x33, 0x8f,
	0x84, 0x6d, 0x23, 0x5a, 0x0f, 0x19, 0xed, 0x5c, 0xe9, 0x57, 0x5b, 0x3f, 0x07, 0x16, 0x79, 0xf2,
	0x27, 0x00, 0x00, 0xff, 0xff, 0x64, 0xec, 0x88, 0xd1, 0xaa, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Get(ctx context.Context, in *UserGetRequest, opts ...grpc.CallOption) (*UserGetResponse, error)
	GetByEmail(ctx context.Context, in *UserGetByEmailRequest, opts ...grpc.CallOption) (*UserGetByEmailResponse, error)
	Create(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserCreateResponse, error)
	VerifyPassword(ctx context.Context, in *UserVerifyPasswordRequest, opts ...grpc.CallOption) (*UserVerifyPasswordResponse, error)
	List(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Get(ctx context.Context, in *UserGetRequest, opts ...grpc.CallOption) (*UserGetResponse, error) {
	out := new(UserGetResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetByEmail(ctx context.Context, in *UserGetByEmailRequest, opts ...grpc.CallOption) (*UserGetByEmailResponse, error) {
	out := new(UserGetByEmailResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/GetByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Create(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserCreateResponse, error) {
	out := new(UserCreateResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) VerifyPassword(ctx context.Context, in *UserVerifyPasswordRequest, opts ...grpc.CallOption) (*UserVerifyPasswordResponse, error) {
	out := new(UserVerifyPasswordResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/VerifyPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) List(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error) {
	out := new(UserListResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Get(context.Context, *UserGetRequest) (*UserGetResponse, error)
	GetByEmail(context.Context, *UserGetByEmailRequest) (*UserGetByEmailResponse, error)
	Create(context.Context, *UserCreateRequest) (*UserCreateResponse, error)
	VerifyPassword(context.Context, *UserVerifyPasswordRequest) (*UserVerifyPasswordResponse, error)
	List(context.Context, *UserListRequest) (*UserListResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Get(ctx, req.(*UserGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/GetByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetByEmail(ctx, req.(*UserGetByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, req.(*UserCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_VerifyPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserVerifyPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).VerifyPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/VerifyPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).VerifyPassword(ctx, req.(*UserVerifyPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).List(ctx, req.(*UserListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _UserService_Get_Handler,
		},
		{
			MethodName: "GetByEmail",
			Handler:    _UserService_GetByEmail_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _UserService_Create_Handler,
		},
		{
			MethodName: "VerifyPassword",
			Handler:    _UserService_VerifyPassword_Handler,
		},
		{
			MethodName: "List",
			Handler:    _UserService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/users.proto",
}
