// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserMeta struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMeta) Reset()         { *m = UserMeta{} }
func (m *UserMeta) String() string { return proto.CompactTextString(m) }
func (*UserMeta) ProtoMessage()    {}
func (*UserMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{0}
}

func (m *UserMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMeta.Unmarshal(m, b)
}
func (m *UserMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMeta.Marshal(b, m, deterministic)
}
func (m *UserMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMeta.Merge(m, src)
}
func (m *UserMeta) XXX_Size() int {
	return xxx_messageInfo_UserMeta.Size(m)
}
func (m *UserMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMeta.DiscardUnknown(m)
}

var xxx_messageInfo_UserMeta proto.InternalMessageInfo

type UserError struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserError) Reset()         { *m = UserError{} }
func (m *UserError) String() string { return proto.CompactTextString(m) }
func (*UserError) ProtoMessage()    {}
func (*UserError) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{1}
}

func (m *UserError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserError.Unmarshal(m, b)
}
func (m *UserError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserError.Marshal(b, m, deterministic)
}
func (m *UserError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserError.Merge(m, src)
}
func (m *UserError) XXX_Size() int {
	return xxx_messageInfo_UserError.Size(m)
}
func (m *UserError) XXX_DiscardUnknown() {
	xxx_messageInfo_UserError.DiscardUnknown(m)
}

var xxx_messageInfo_UserError proto.InternalMessageInfo

func (m *UserError) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Verified             bool     `protobuf:"varint,5,opt,name=verified,proto3" json:"verified,omitempty"`
	CreatedAt            int64    `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *User) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *User) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type UserGetRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGetRequest) Reset()         { *m = UserGetRequest{} }
func (m *UserGetRequest) String() string { return proto.CompactTextString(m) }
func (*UserGetRequest) ProtoMessage()    {}
func (*UserGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{3}
}

func (m *UserGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetRequest.Unmarshal(m, b)
}
func (m *UserGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetRequest.Marshal(b, m, deterministic)
}
func (m *UserGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetRequest.Merge(m, src)
}
func (m *UserGetRequest) XXX_Size() int {
	return xxx_messageInfo_UserGetRequest.Size(m)
}
func (m *UserGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetRequest proto.InternalMessageInfo

func (m *UserGetRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UserGetResponse struct {
	Data                 *User      `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 *UserMeta  `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *UserError `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserGetResponse) Reset()         { *m = UserGetResponse{} }
func (m *UserGetResponse) String() string { return proto.CompactTextString(m) }
func (*UserGetResponse) ProtoMessage()    {}
func (*UserGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{4}
}

func (m *UserGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetResponse.Unmarshal(m, b)
}
func (m *UserGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetResponse.Marshal(b, m, deterministic)
}
func (m *UserGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetResponse.Merge(m, src)
}
func (m *UserGetResponse) XXX_Size() int {
	return xxx_messageInfo_UserGetResponse.Size(m)
}
func (m *UserGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetResponse proto.InternalMessageInfo

func (m *UserGetResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserGetResponse) GetMeta() *UserMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *UserGetResponse) GetError() *UserError {
	if m != nil {
		return m.Error
	}
	return nil
}

type UserGetByEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGetByEmailRequest) Reset()         { *m = UserGetByEmailRequest{} }
func (m *UserGetByEmailRequest) String() string { return proto.CompactTextString(m) }
func (*UserGetByEmailRequest) ProtoMessage()    {}
func (*UserGetByEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{5}
}

func (m *UserGetByEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetByEmailRequest.Unmarshal(m, b)
}
func (m *UserGetByEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetByEmailRequest.Marshal(b, m, deterministic)
}
func (m *UserGetByEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetByEmailRequest.Merge(m, src)
}
func (m *UserGetByEmailRequest) XXX_Size() int {
	return xxx_messageInfo_UserGetByEmailRequest.Size(m)
}
func (m *UserGetByEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetByEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetByEmailRequest proto.InternalMessageInfo

func (m *UserGetByEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UserGetByEmailResponse struct {
	Data                 *User      `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 *UserMeta  `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *UserError `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserGetByEmailResponse) Reset()         { *m = UserGetByEmailResponse{} }
func (m *UserGetByEmailResponse) String() string { return proto.CompactTextString(m) }
func (*UserGetByEmailResponse) ProtoMessage()    {}
func (*UserGetByEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{6}
}

func (m *UserGetByEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetByEmailResponse.Unmarshal(m, b)
}
func (m *UserGetByEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetByEmailResponse.Marshal(b, m, deterministic)
}
func (m *UserGetByEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetByEmailResponse.Merge(m, src)
}
func (m *UserGetByEmailResponse) XXX_Size() int {
	return xxx_messageInfo_UserGetByEmailResponse.Size(m)
}
func (m *UserGetByEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetByEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetByEmailResponse proto.InternalMessageInfo

func (m *UserGetByEmailResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserGetByEmailResponse) GetMeta() *UserMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *UserGetByEmailResponse) GetError() *UserError {
	if m != nil {
		return m.Error
	}
	return nil
}

type UserCreateRequest struct {
	Data                 *User    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreateRequest) Reset()         { *m = UserCreateRequest{} }
func (m *UserCreateRequest) String() string { return proto.CompactTextString(m) }
func (*UserCreateRequest) ProtoMessage()    {}
func (*UserCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{7}
}

func (m *UserCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreateRequest.Unmarshal(m, b)
}
func (m *UserCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreateRequest.Marshal(b, m, deterministic)
}
func (m *UserCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreateRequest.Merge(m, src)
}
func (m *UserCreateRequest) XXX_Size() int {
	return xxx_messageInfo_UserCreateRequest.Size(m)
}
func (m *UserCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreateRequest proto.InternalMessageInfo

func (m *UserCreateRequest) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserCreateResponse struct {
	Data                 *User      `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 *UserMeta  `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *UserError `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserCreateResponse) Reset()         { *m = UserCreateResponse{} }
func (m *UserCreateResponse) String() string { return proto.CompactTextString(m) }
func (*UserCreateResponse) ProtoMessage()    {}
func (*UserCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{8}
}

func (m *UserCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreateResponse.Unmarshal(m, b)
}
func (m *UserCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreateResponse.Marshal(b, m, deterministic)
}
func (m *UserCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreateResponse.Merge(m, src)
}
func (m *UserCreateResponse) XXX_Size() int {
	return xxx_messageInfo_UserCreateResponse.Size(m)
}
func (m *UserCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreateResponse proto.InternalMessageInfo

func (m *UserCreateResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserCreateResponse) GetMeta() *UserMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *UserCreateResponse) GetError() *UserError {
	if m != nil {
		return m.Error
	}
	return nil
}

type UserVerifyPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserVerifyPasswordRequest) Reset()         { *m = UserVerifyPasswordRequest{} }
func (m *UserVerifyPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*UserVerifyPasswordRequest) ProtoMessage()    {}
func (*UserVerifyPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{9}
}

func (m *UserVerifyPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserVerifyPasswordRequest.Unmarshal(m, b)
}
func (m *UserVerifyPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserVerifyPasswordRequest.Marshal(b, m, deterministic)
}
func (m *UserVerifyPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserVerifyPasswordRequest.Merge(m, src)
}
func (m *UserVerifyPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_UserVerifyPasswordRequest.Size(m)
}
func (m *UserVerifyPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserVerifyPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserVerifyPasswordRequest proto.InternalMessageInfo

func (m *UserVerifyPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserVerifyPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserVerifyPasswordResponse struct {
	Data                 *User      `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 *UserMeta  `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *UserError `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserVerifyPasswordResponse) Reset()         { *m = UserVerifyPasswordResponse{} }
func (m *UserVerifyPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*UserVerifyPasswordResponse) ProtoMessage()    {}
func (*UserVerifyPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{10}
}

func (m *UserVerifyPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserVerifyPasswordResponse.Unmarshal(m, b)
}
func (m *UserVerifyPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserVerifyPasswordResponse.Marshal(b, m, deterministic)
}
func (m *UserVerifyPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserVerifyPasswordResponse.Merge(m, src)
}
func (m *UserVerifyPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_UserVerifyPasswordResponse.Size(m)
}
func (m *UserVerifyPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserVerifyPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserVerifyPasswordResponse proto.InternalMessageInfo

func (m *UserVerifyPasswordResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserVerifyPasswordResponse) GetMeta() *UserMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *UserVerifyPasswordResponse) GetError() *UserError {
	if m != nil {
		return m.Error
	}
	return nil
}

type UserListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListRequest) Reset()         { *m = UserListRequest{} }
func (m *UserListRequest) String() string { return proto.CompactTextString(m) }
func (*UserListRequest) ProtoMessage()    {}
func (*UserListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{11}
}

func (m *UserListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListRequest.Unmarshal(m, b)
}
func (m *UserListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListRequest.Marshal(b, m, deterministic)
}
func (m *UserListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListRequest.Merge(m, src)
}
func (m *UserListRequest) XXX_Size() int {
	return xxx_messageInfo_UserListRequest.Size(m)
}
func (m *UserListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserListRequest proto.InternalMessageInfo

type UserListResponse struct {
	Data                 []*User    `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Meta                 *UserMeta  `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *UserError `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserListResponse) Reset()         { *m = UserListResponse{} }
func (m *UserListResponse) String() string { return proto.CompactTextString(m) }
func (*UserListResponse) ProtoMessage()    {}
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{12}
}

func (m *UserListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListResponse.Unmarshal(m, b)
}
func (m *UserListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListResponse.Marshal(b, m, deterministic)
}
func (m *UserListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListResponse.Merge(m, src)
}
func (m *UserListResponse) XXX_Size() int {
	return xxx_messageInfo_UserListResponse.Size(m)
}
func (m *UserListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserListResponse proto.InternalMessageInfo

func (m *UserListResponse) GetData() []*User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserListResponse) GetMeta() *UserMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *UserListResponse) GetError() *UserError {
	if m != nil {
		return m.Error
	}
	return nil
}

type UserUpdateRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Data                 *User    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserUpdateRequest) Reset()         { *m = UserUpdateRequest{} }
func (m *UserUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UserUpdateRequest) ProtoMessage()    {}
func (*UserUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{13}
}

func (m *UserUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUpdateRequest.Unmarshal(m, b)
}
func (m *UserUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUpdateRequest.Marshal(b, m, deterministic)
}
func (m *UserUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUpdateRequest.Merge(m, src)
}
func (m *UserUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UserUpdateRequest.Size(m)
}
func (m *UserUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserUpdateRequest proto.InternalMessageInfo

func (m *UserUpdateRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserUpdateRequest) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserUpdateResponse struct {
	Data                 *User      `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 *UserMeta  `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *UserError `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserUpdateResponse) Reset()         { *m = UserUpdateResponse{} }
func (m *UserUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UserUpdateResponse) ProtoMessage()    {}
func (*UserUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{14}
}

func (m *UserUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUpdateResponse.Unmarshal(m, b)
}
func (m *UserUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUpdateResponse.Marshal(b, m, deterministic)
}
func (m *UserUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUpdateResponse.Merge(m, src)
}
func (m *UserUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UserUpdateResponse.Size(m)
}
func (m *UserUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserUpdateResponse proto.InternalMessageInfo

func (m *UserUpdateResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserUpdateResponse) GetMeta() *UserMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *UserUpdateResponse) GetError() *UserError {
	if m != nil {
		return m.Error
	}
	return nil
}

type UserDeleteRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDeleteRequest) Reset()         { *m = UserDeleteRequest{} }
func (m *UserDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*UserDeleteRequest) ProtoMessage()    {}
func (*UserDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{15}
}

func (m *UserDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDeleteRequest.Unmarshal(m, b)
}
func (m *UserDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDeleteRequest.Marshal(b, m, deterministic)
}
func (m *UserDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDeleteRequest.Merge(m, src)
}
func (m *UserDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_UserDeleteRequest.Size(m)
}
func (m *UserDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserDeleteRequest proto.InternalMessageInfo

func (m *UserDeleteRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UserDeleteResponse struct {
	Data                 *User      `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 *UserMeta  `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *UserError `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserDeleteResponse) Reset()         { *m = UserDeleteResponse{} }
func (m *UserDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*UserDeleteResponse) ProtoMessage()    {}
func (*UserDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{16}
}

func (m *UserDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDeleteResponse.Unmarshal(m, b)
}
func (m *UserDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDeleteResponse.Marshal(b, m, deterministic)
}
func (m *UserDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDeleteResponse.Merge(m, src)
}
func (m *UserDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_UserDeleteResponse.Size(m)
}
func (m *UserDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserDeleteResponse proto.InternalMessageInfo

func (m *UserDeleteResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserDeleteResponse) GetMeta() *UserMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *UserDeleteResponse) GetError() *UserError {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*UserMeta)(nil), "proto.UserMeta")
	proto.RegisterType((*UserError)(nil), "proto.UserError")
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*UserGetRequest)(nil), "proto.UserGetRequest")
	proto.RegisterType((*UserGetResponse)(nil), "proto.UserGetResponse")
	proto.RegisterType((*UserGetByEmailRequest)(nil), "proto.UserGetByEmailRequest")
	proto.RegisterType((*UserGetByEmailResponse)(nil), "proto.UserGetByEmailResponse")
	proto.RegisterType((*UserCreateRequest)(nil), "proto.UserCreateRequest")
	proto.RegisterType((*UserCreateResponse)(nil), "proto.UserCreateResponse")
	proto.RegisterType((*UserVerifyPasswordRequest)(nil), "proto.UserVerifyPasswordRequest")
	proto.RegisterType((*UserVerifyPasswordResponse)(nil), "proto.UserVerifyPasswordResponse")
	proto.RegisterType((*UserListRequest)(nil), "proto.UserListRequest")
	proto.RegisterType((*UserListResponse)(nil), "proto.UserListResponse")
	proto.RegisterType((*UserUpdateRequest)(nil), "proto.UserUpdateRequest")
	proto.RegisterType((*UserUpdateResponse)(nil), "proto.UserUpdateResponse")
	proto.RegisterType((*UserDeleteRequest)(nil), "proto.UserDeleteRequest")
	proto.RegisterType((*UserDeleteResponse)(nil), "proto.UserDeleteResponse")
}

func init() {
	proto.RegisterFile("users.proto", fileDescriptor_030765f334c86cea)
}

var fileDescriptor_030765f334c86cea = []byte{
	// 571 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0x41, 0x6b, 0x13, 0x41,
	0x14, 0xee, 0x24, 0x9b, 0x34, 0x79, 0x0b, 0x69, 0xfb, 0xb0, 0xed, 0x76, 0xb1, 0x18, 0x47, 0x90,
	0x08, 0xda, 0x43, 0x14, 0xa1, 0x27, 0xa9, 0x5a, 0x8a, 0x68, 0x41, 0x56, 0xaa, 0xc7, 0xb2, 0x66,
	0x9f, 0xb2, 0xd0, 0x74, 0xe3, 0xce, 0xa4, 0xd2, 0x93, 0xe2, 0xc1, 0x83, 0x3f, 0xc8, 0xff, 0xe4,
	0xbf, 0x90, 0x99, 0xc9, 0x4e, 0x66, 0xda, 0xd8, 0xdc, 0xdc, 0x53, 0x76, 0xde, 0xf7, 0xcd, 0xe3,
	0x7b, 0x5f, 0xbe, 0x37, 0x10, 0x4e, 0x05, 0x95, 0x62, 0x6f, 0x52, 0x16, 0xb2, 0xc0, 0x96, 0xfe,
	0xe1, 0x00, 0x9d, 0x13, 0x41, 0xe5, 0x31, 0xc9, 0x94, 0xef, 0x43, 0x57, 0x7d, 0x1f, 0x96, 0x65,
	0x51, 0x22, 0x42, 0x30, 0x2a, 0x32, 0x8a, 0x58, 0x9f, 0x0d, 0x5a, 0x89, 0xfe, 0xc6, 0x08, 0x56,
	0xc7, 0x24, 0x44, 0xfa, 0x99, 0xa2, 0x46, 0x9f, 0x0d, 0xba, 0x49, 0x75, 0xe4, 0xbf, 0x19, 0x04,
	0xea, 0x2e, 0xf6, 0xa0, 0x91, 0x67, 0xfa, 0x52, 0x37, 0x69, 0xe4, 0x99, 0x6a, 0x73, 0x9e, 0x8e,
	0x2b, 0xbe, 0xfe, 0xc6, 0x5b, 0xd0, 0xa2, 0x71, 0x9a, 0x9f, 0x45, 0x4d, 0x5d, 0x34, 0x07, 0x8c,
	0xa1, 0x33, 0x49, 0x85, 0xf8, 0x5a, 0x94, 0x59, 0x14, 0x68, 0xc0, 0x9e, 0x15, 0x76, 0x41, 0x65,
	0xfe, 0x29, 0xa7, 0x2c, 0x6a, 0xf5, 0xd9, 0xa0, 0x93, 0xd8, 0x33, 0xee, 0x02, 0x8c, 0x4a, 0x4a,
	0x25, 0x65, 0xa7, 0xa9, 0x8c, 0xda, 0x7d, 0x36, 0x68, 0x26, 0xdd, 0x59, 0xe5, 0x40, 0x2a, 0x78,
	0x3a, 0xc9, 0x2a, 0x78, 0xd5, 0xc0, 0xb3, 0xca, 0x81, 0xe4, 0x0f, 0xa0, 0xa7, 0x74, 0x1f, 0x91,
	0x4c, 0xe8, 0xcb, 0x94, 0x84, 0xc4, 0x6d, 0x58, 0x55, 0x3e, 0x9d, 0xda, 0x31, 0xda, 0xea, 0xf8,
	0x2a, 0xe3, 0xdf, 0x60, 0xcd, 0x52, 0xc5, 0xa4, 0x38, 0x17, 0x84, 0x77, 0x20, 0xc8, 0x52, 0x99,
	0x6a, 0x62, 0x38, 0x0c, 0x8d, 0xb5, 0x7b, 0x8a, 0x95, 0x68, 0x00, 0xef, 0x41, 0x30, 0x26, 0x99,
	0xea, 0xf1, 0xc3, 0xe1, 0x9a, 0x43, 0x50, 0x8e, 0x27, 0x1a, 0xc4, 0xfb, 0xd0, 0x22, 0xe5, 0xb9,
	0xf6, 0x23, 0x1c, 0xae, 0x3b, 0x2c, 0xfd, 0x5f, 0x24, 0x06, 0xe6, 0x8f, 0x60, 0x73, 0x26, 0xe0,
	0xf9, 0xe5, 0xa1, 0xf2, 0xac, 0x92, 0x6c, 0x0d, 0x65, 0x8e, 0xa1, 0xfc, 0x27, 0x83, 0xad, 0xab,
	0xfc, 0x5a, 0x74, 0x3f, 0x81, 0x0d, 0x55, 0x7b, 0xa1, 0xff, 0x93, 0x4a, 0xf3, 0x32, 0x09, 0xfc,
	0x07, 0x03, 0x74, 0xaf, 0xd5, 0x22, 0xfd, 0x18, 0x76, 0x54, 0xed, 0xbd, 0x0a, 0xdb, 0xe5, 0xdb,
	0x59, 0x1c, 0x6f, 0xb4, 0xdd, 0xcb, 0x71, 0xc3, 0xcf, 0x31, 0xff, 0xc5, 0x20, 0x5e, 0xd4, 0xaf,
	0x96, 0xd9, 0x36, 0x4c, 0x9e, 0xdf, 0xe4, 0xa2, 0xca, 0x3e, 0xff, 0xce, 0x60, 0x7d, 0x5e, 0xbb,
	0xa6, 0xaa, 0xf9, 0x5f, 0x1c, 0xd7, 0x61, 0x39, 0xd1, 0x1b, 0xba, 0x6c, 0x27, 0xad, 0xb6, 0xc6,
	0xb2, 0x14, 0x55, 0xfd, 0x6a, 0x71, 0xfa, 0xa1, 0x99, 0xe9, 0x25, 0x9d, 0xd1, 0xf2, 0x99, 0xac,
	0xe4, 0x8a, 0x5e, 0x87, 0xe4, 0xe1, 0x9f, 0x26, 0x84, 0xaa, 0xf8, 0x8e, 0xca, 0x8b, 0x7c, 0x44,
	0xf8, 0x14, 0x9a, 0x47, 0x24, 0x71, 0xd3, 0xe1, 0xcf, 0xdf, 0xcc, 0x78, 0xeb, 0x6a, 0xd9, 0x68,
	0xe6, 0x2b, 0xf8, 0x1a, 0x60, 0xfe, 0xfe, 0xe0, 0x6d, 0x9f, 0xe7, 0x3f, 0x63, 0xf1, 0xee, 0x3f,
	0x50, 0xdb, 0xec, 0x19, 0xb4, 0xcd, 0x6b, 0x80, 0x91, 0x43, 0xf5, 0xde, 0x95, 0x78, 0x67, 0x01,
	0x62, 0x1b, 0x7c, 0x80, 0x9e, 0xbf, 0x7a, 0xd8, 0x77, 0xe8, 0x0b, 0xb7, 0x3c, 0xbe, 0x7b, 0x03,
	0xc3, 0x36, 0xde, 0x87, 0x40, 0xed, 0x0c, 0xba, 0x46, 0x38, 0x8b, 0x15, 0x6f, 0x5f, 0xab, 0xbb,
	0x43, 0x99, 0x70, 0x7a, 0x43, 0x79, 0xf9, 0xf7, 0x86, 0xf2, 0x93, 0x6c, 0x1a, 0x98, 0xa8, 0x78,
	0x0d, 0xbc, 0xb0, 0x79, 0x0d, 0xfc, 0x5c, 0xf1, 0x95, 0x8f, 0x6d, 0x8d, 0x3d, 0xfe, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0xdc, 0x34, 0x18, 0x01, 0x20, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Get(ctx context.Context, in *UserGetRequest, opts ...grpc.CallOption) (*UserGetResponse, error)
	GetByEmail(ctx context.Context, in *UserGetByEmailRequest, opts ...grpc.CallOption) (*UserGetByEmailResponse, error)
	Create(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserCreateResponse, error)
	VerifyPassword(ctx context.Context, in *UserVerifyPasswordRequest, opts ...grpc.CallOption) (*UserVerifyPasswordResponse, error)
	List(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error)
	Update(ctx context.Context, in *UserUpdateRequest, opts ...grpc.CallOption) (*UserUpdateResponse, error)
	Delete(ctx context.Context, in *UserDeleteRequest, opts ...grpc.CallOption) (*UserDeleteResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Get(ctx context.Context, in *UserGetRequest, opts ...grpc.CallOption) (*UserGetResponse, error) {
	out := new(UserGetResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetByEmail(ctx context.Context, in *UserGetByEmailRequest, opts ...grpc.CallOption) (*UserGetByEmailResponse, error) {
	out := new(UserGetByEmailResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/GetByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Create(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserCreateResponse, error) {
	out := new(UserCreateResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) VerifyPassword(ctx context.Context, in *UserVerifyPasswordRequest, opts ...grpc.CallOption) (*UserVerifyPasswordResponse, error) {
	out := new(UserVerifyPasswordResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/VerifyPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) List(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error) {
	out := new(UserListResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Update(ctx context.Context, in *UserUpdateRequest, opts ...grpc.CallOption) (*UserUpdateResponse, error) {
	out := new(UserUpdateResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Delete(ctx context.Context, in *UserDeleteRequest, opts ...grpc.CallOption) (*UserDeleteResponse, error) {
	out := new(UserDeleteResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Get(context.Context, *UserGetRequest) (*UserGetResponse, error)
	GetByEmail(context.Context, *UserGetByEmailRequest) (*UserGetByEmailResponse, error)
	Create(context.Context, *UserCreateRequest) (*UserCreateResponse, error)
	VerifyPassword(context.Context, *UserVerifyPasswordRequest) (*UserVerifyPasswordResponse, error)
	List(context.Context, *UserListRequest) (*UserListResponse, error)
	Update(context.Context, *UserUpdateRequest) (*UserUpdateResponse, error)
	Delete(context.Context, *UserDeleteRequest) (*UserDeleteResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Get(ctx context.Context, req *UserGetRequest) (*UserGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedUserServiceServer) GetByEmail(ctx context.Context, req *UserGetByEmailRequest) (*UserGetByEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByEmail not implemented")
}
func (*UnimplementedUserServiceServer) Create(ctx context.Context, req *UserCreateRequest) (*UserCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedUserServiceServer) VerifyPassword(ctx context.Context, req *UserVerifyPasswordRequest) (*UserVerifyPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyPassword not implemented")
}
func (*UnimplementedUserServiceServer) List(ctx context.Context, req *UserListRequest) (*UserListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedUserServiceServer) Update(ctx context.Context, req *UserUpdateRequest) (*UserUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedUserServiceServer) Delete(ctx context.Context, req *UserDeleteRequest) (*UserDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Get(ctx, req.(*UserGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/GetByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetByEmail(ctx, req.(*UserGetByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, req.(*UserCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_VerifyPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserVerifyPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).VerifyPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/VerifyPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).VerifyPassword(ctx, req.(*UserVerifyPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).List(ctx, req.(*UserListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Update(ctx, req.(*UserUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Delete(ctx, req.(*UserDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _UserService_Get_Handler,
		},
		{
			MethodName: "GetByEmail",
			Handler:    _UserService_GetByEmail_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _UserService_Create_Handler,
		},
		{
			MethodName: "VerifyPassword",
			Handler:    _UserService_VerifyPassword_Handler,
		},
		{
			MethodName: "List",
			Handler:    _UserService_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UserService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users.proto",
}
